### ISSUE TITLE
Support advanced flow types

### ISSUE THREAD

**Issue by aldendaniels** [zertosh/eslint-plugin-flow-vars#2]
Thanks for this very useful library. Great to have seamless linting of flow-annotated code!

ESLint is complaining that `$Shape is not defined (no-undef)`. See http://sitr.us/2015/05/31/advanced-features-in-flow.html for a list of useful (although still undocumented) advanced types in flow.

**Comment by zertosh** [comment]
I've [deprecated](https://github.com/zertosh/eslint-plugin-flow-vars#this-project-is-deprecated) the project in favor of [eslint-plugin-flowtype](https://github.com/gajus/eslint-plugin-flowtype). I ported the exact same functionality over since it made for sense for there to be only one plugin for flow related linting.

I recommend that you re-file the issue there.
