### ISSUE TITLE
Suppress duplicate import when one is normal import and second is type import

### ISSUE THREAD

**Issue by dj-foxxy** [zertosh/eslint-plugin-flow-vars#6]
Hi, great package. Works as advertised.

I have no idea if this can be implemented but it would be cool to suppress this:

```
import { Foo } from './foo.js';
import type { Bar } from './foo.js';  // <- ESLint warns for duplicate import
```

At the moment, we explicitly suppress the warning with `// eslint-disable-next-line no-duplicate-imports`

**Comment by zertosh** [comment]
I've [deprecated](https://github.com/zertosh/eslint-plugin-flow-vars#this-project-is-deprecated) the project in favor of [eslint-plugin-flowtype](https://github.com/gajus/eslint-plugin-flowtype). I ported the exact same functionality over since it made for sense for there to be only one plugin for flow related linting.

I recommend that you re-file the issue there.
