### ISSUE TITLE
Add a Changelog?

### ISSUE THREAD

**Issue by lencioni** [zertosh/eslint-plugin-flow-vars#8]
When updating, it would be really useful to have a list of the changes included in each release somewhere. This will make it easier to know how to best handle the update (e.g. enable new rules).

**Comment by zertosh** [comment]
Sorry for any inconvenience this caused you. It's a moot point now since I've [deprecated](https://github.com/zertosh/eslint-plugin-flow-vars#this-project-is-deprecated) the project in favor of [eslint-plugin-flowtype](https://github.com/gajus/eslint-plugin-flowtype). I ported the exact same functionality over since it made for sense for there to be only one plugin for flow related linting.

**Comment by lencioni** [comment]
No worries! Thanks for the response. :)
